CREATE TABLE tuser(
	id INT PRIMARY KEY AUTO_INCREMENT,
	nama VARCHAR(255),
	jenis_kelamin VARCHAR(100),
	ttl TEXT,
	nim TEXT,
	ipk DOUBLE,
	jurusan VARCHAR(200),
	univ TEXT,
	tahun_masuk INTEGER,
	nomor_rekening TEXT,
	nomor_hp TEXT,
	ket TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
